# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CalendarProject.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.calendar_1 = QtWidgets.QCalendarWidget(self.centralwidget)
        self.calendar_1.setGeometry(QtCore.QRect(210, 80, 381, 371))
        self.calendar_1.setObjectName("calendar_1")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuopen = QtWidgets.QMenu(self.menufile)
        self.menuopen.setObjectName("menuopen")
        self.menuShare = QtWidgets.QMenu(self.menufile)
        self.menuShare.setObjectName("menuShare")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionPenis = QtWidgets.QAction(MainWindow)
        self.actionPenis.setObjectName("actionPenis")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionHoliday = QtWidgets.QAction(MainWindow)
        self.actionHoliday.setObjectName("actionHoliday")
        self.actionBirthday = QtWidgets.QAction(MainWindow)
        self.actionBirthday.setObjectName("actionBirthday")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionWidgets = QtWidgets.QAction(MainWindow)
        self.actionWidgets.setObjectName("actionWidgets")
        self.actionBeta = QtWidgets.QAction(MainWindow)
        self.actionBeta.setObjectName("actionBeta")
        self.menuopen.addAction(self.actionPenis)
        self.menuopen.addAction(self.actionHoliday)
        self.menuopen.addAction(self.actionBirthday)
        self.menuopen.addSeparator()
        self.menuShare.addAction(self.actionBeta)
        self.menuShare.addSeparator()
        self.menufile.addAction(self.menuopen.menuAction())
        self.menufile.addAction(self.actionOpen)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionSave)
        self.menufile.addAction(self.actionSave_As)
        self.menufile.addAction(self.menuShare.menuAction())
        self.menuTools.addAction(self.actionPreferences)
        self.menuTools.addAction(self.actionWidgets)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menufile.setTitle(_translate("MainWindow", "File"))
        self.menuopen.setTitle(_translate("MainWindow", "New"))
        self.menuShare.setTitle(_translate("MainWindow", "Share"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.actionPenis.setText(_translate("MainWindow", "Event"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionHoliday.setText(_translate("MainWindow", "Holiday"))
        self.actionBirthday.setText(_translate("MainWindow", "Birthday"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionWidgets.setText(_translate("MainWindow", "Widgets"))
        self.actionBeta.setText(_translate("MainWindow", "Beta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
